
PARTDESCRIPTION := { COMMENTLINE+ | NAMEDEFINITION+ | ASSIGNMENT+ | OPERATION+ | COMMAND+ }+

COMMENTLINE := "#" {[LETTER+] | [DIGIT+] | [SPACE+]}+


NAMEDEFINITION :=
	TYPE ["ARRAY"] NAME ["{" VALUE "}"] ";"


TYPE := "SOC" | "DOT" | "POINT" | "LINE" | "VECTOR" | "ANGLE" | "RECTANGLE" | "CONTOUR" | "PLANE" | "CIRCLE" | 
		"ARC" | "ELLIPSE" | "SECTOR" | "SPLINE" | "SURFACE" | "BODY" | "INTEGER" | "REAL"

NAME :=  LETTER+ [LETTER+ | DIGIT+] 

LETTER := "A" .. "Z" | "a" .. "z"

SPACE := " "

DIGIT := "0" .. "9"

VALUE := 
	NUMBER [{"," NUMBER}] | EXPRESSION [{"," EXPRESSION}] | OPERATION [{"," OPERATION}] | KEYWORD [{"," KEYWORD}]

KEYWORDLIST :=
	"DEFAULT" | "RIGHT" | "LEFT" | "RIGHTHANDED" | "LEFTHANDED" | "M" |"MM" | "INCH" 

EXPRESSION := 
	NAME | TYPE ["ARRAY"] "{" VALUE "}" | MATHEXPRESSION 

MATHEXPRESSION := 
	TERM { ADDITION TERM } | UNARSIGN MATHEXPRESSION

TERM := 
	FACTOR  {MULTIPLICATION FACTOR}

FACTOR := 
	POWER {POWEROPERATOR POWER}

POWER := 
	EXPRESSION | "(" EXPRESSION ")"

ADDITION :=
	"+" | "-" 

MULTIPLICATION :=
	"/" | "*"

POWEROPERATOR := "^"


NUMBER :=
	[UNARSIGN] DIGIT+,["."][DIGIT+]

UNARSIGN :=	"+" | "-"

ASSIGNMENT := NAME [ [{"." NAME}] [{"." FIELD} | {"[" INDEX "]"}]] "=" EXPRESSION ";x"

FIELD :=
	"X" | "Y" | "Z" | "COLOR" | "VISIBILITY" | "STYLE"  

INDEX := DIGIT+


OPERATION :=
	[NAME =] ACTION "(" VALUE ")" | 


ACTION := 
	"NORMALE" | "DISTANCE" | "ROTATE" | "MIRROR" | "MOVE" | "INVERSE" |
	"EXTRUDE" | "JOIN" | "SUBTRACT" | "INTERSECT" | "FILL" | 
	"WRITE" | "READ" | "READNEXT" | "OVERWRITE" | "READAGAIN" 

COMMAND :=
	"SHOW" NAME | "HIDE" NAME |
	"DO" ITERATOR "=" STARTINDEX "," ENDIXDEX  ["," STEP ] ";"  {ASSIGNMENT+ | OPERATION+ | COMMAND+}+ "LOOP" ITERATOR ";"

STARTINDEX :=  DIGIT+

ENDIXDEX :=  DIGIT+

STEP := [UNARSIGN] DIGIT+

ITERATOR := NAME 


